apiVersion: v1
kind: Service
metadata:
  name: mygoapp
spec:
  type: NodePort
  selector:
    app: mygoapp
  ports:
    - name: http
      port: 80
      targetPort: 8020
      nodePort: 30000
      protocol: TCP
